{% set name = "asimov-gwdata" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asimov-gwdata-{{ version }}.tar.gz
  sha256: f382ccb6f689334ad2b471799bbfa3f13aafb6cfae6d6f63184e456edcf0f988

build:
  entry_points:
    - gwdata = datafind.main:get_data
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >=3.7
    - gwosc
    - asimov >=0.4.0
    - pesummary

test:
  imports:
    - datafind
  commands:
    - pip check
    - gwdata --help
  requires:
    - pip

about:
  home: https://git.ligo.org/asimov/pipelines/gwdata
  summary: An asimov plugin to make downloading gravitational wave data easier
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - transientlunatic
    - mj-will
